<?php
$z[0]=Array("global","",2050,2077);
$z[0][4]=array();
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",3443,3470);
$z[1][4]=array();
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("channel"," \n                        <a href=\"[field:typeurl/]\">[field:typename/]</a> \n                        ",3589,3737);
$z[2][4]=array();
$z[2][4]['type']="top";
$z[2][4]['row']="5";
$z[3]=Array("global","",4239,4266);
$z[3][4]=array();
$z[3][4]['name']="cfg_basehost";

?>